public enum SoundEffectType
{
    GRAB_BLOCK,
    CANCEL_BLOCK,
    POSE_BLOCK,
    DEFEAT,
    TIC_TAC,
    TRUCK_ARRIVE,
    TRUCK_REPART,
    BUTTON_CLICK_IN,
    BUTTON_CLICK_OUT,
    BUTTON_CLICK_HOVER,
    TRUCK_STEP_LOADING,
    OUTCH,
    CLIC,
    OVER,
    PLANESCORE,
    PERFECTSCORE,

    PLACE_SCORE
}